image: node:19.2

stages:
  - build
  - test
  - package

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir .pnpm-store
  - pnpm install

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

build-job:
  stage: build
  script:
    - pnpm run esbuild-base

test-job:
  stage: test
  script:
    - pnpm run test

lint-job:
  stage: test
  script:
    - pnpm run lint

validate-job:
  stage: test
  script:
    - git clone -n --shallow-exclude=2022-09 https://github.com/Systems-Modeling/SysML-v2-Release.git
    - cd SysML-v2-Release
    - git checkout tags/2022-10
    - cd ..
    - pnpm run run-validation

package-job:
  stage: package
  environment: production
  variables:
    EXTENSION_NAME: sensmetry.sysml-2ls-${CI_COMMIT_SHA}
  script:
    - pnpm run vscode:package -o "$EXTENSION_NAME.vsix"
  artifacts:
    paths:
      - $EXTENSION_NAME.vsix
    name: $EXTENSION_NAME
    expire_in: 1 mos
