packages:
  - "packages/syside-base"
  - "packages/syside-languageserver"
  - "packages/syside-cli"
  - "packages/syside-languageclient"
  - "packages/syside-protocol"
  - "packages/syside-vscode"
  - "packages/sysml-agree"